on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          cd src/python &&
          pip install -r requirements.txt

  golang-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"
      - name: Build Golang code
        run: go build go/tweets_scraper.go
      - name: Run Golang tests
        run: go test go/...
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: "v1.42.1"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter@v5
        with:
          validation: true
          strict: true
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: ${{ github.head_ref || github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
