name: super-linter
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install depedencies
        run: |
          cd src/python &&
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}